### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by DominikGeimer** [fabpl/zephyr#1]
Hello,

I get the following error when I try to install your package. I am on a new Laravel 9 app.

[InvalidArgumentException]
  Could not find a matching version of package fabpl/zephyr. Check the package spelling, your version constraint and
  that the package is available in a stability which matches your minimum-stability (dev).

**Comment by fabpl** [comment]
Hello,

can you try using 1.0 tag ?
composer install "fabpl/zephyr@1.0"  ?
